// Maps team / country names used in the app to ISO 3166-1 alpha-2 codes
// used by `country-flag-icons` for SVG flag rendering.
export const teamToCountryCode: Record<string, string> = {
  Brazil: "BR",
  Argentina: "AR",
  France: "FR",
  Germany: "DE",
  Spain: "ES",
  England: "GB", // country-flag-icons uses GB for England
  Portugal: "PT",
  Netherlands: "NL",
  Italy: "IT",
  Belgium: "BE",
  Japan: "JP",
  "South Korea": "KR",
  USA: "US",
  Mexico: "MX",
  Canada: "CA",
  Morocco: "MA",
  Senegal: "SN",
  Nigeria: "NG",
  Ghana: "GH",
  Cameroon: "CM",
  Australia: "AU",
  "Saudi Arabia": "SA",
  Uruguay: "UY",
  Croatia: "HR",
  Colombia: "CO",
  Ecuador: "EC",
  Switzerland: "CH",
  Denmark: "DK",
  Serbia: "RS",
  Poland: "PL",
  Tunisia: "TN",
  "Costa Rica": "CR",
  "South Africa": "ZA",
  Czechia: "CZ",
  "Bosnia and Herzegovina": "BA",
  Paraguay: "PY",
  Qatar: "QA",
  Haiti: "HT",
  Scotland: "GB-SCT",
  Turkiye: "TR",
  Curacao: "CW",
  "Ivory Coast": "CI",
  Sweden: "SE",
  "Cape Verde": "CV",
  Egypt: "EG",
  Iran: "IR",
  "New Zealand": "NZ",
  Iraq: "IQ",
  Norway: "NO",
  Algeria: "DZ",
  Austria: "AT",
  Jordan: "JO",
  "DR Congo": "CD",
  Panama: "PA",
  Uzbekistan: "UZ",
};

export function getTeamCountryCode(teamName: string): string | null {
  return teamToCountryCode[teamName] ?? null;
}
