/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-tickets': typeof MyTicketsRoute
  '/profile': typeof ProfileRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-tickets': typeof MyTicketsRoute
  '/profile': typeof ProfileRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/matches': typeof MatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-tickets': typeof MyTicketsRoute
  '/profile': typeof ProfileRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/my-tickets'
    | '/profile'
    | '/checkout/success'
    | '/matches/$matchId'
    | '/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/my-tickets'
    | '/profile'
    | '/checkout/success'
    | '/matches/$matchId'
    | '/matches'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/my-tickets'
    | '/profile'
    | '/checkout/success'
    | '/matches/$matchId'
    | '/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MyTicketsRoute: typeof MyTicketsRoute
  ProfileRoute: typeof ProfileRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MyTicketsRoute: MyTicketsRoute,
  ProfileRoute: ProfileRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
